<?php

use Elgentos\Convert\ViewModel\Convert;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Convert $config */
$config = $viewModels->require(Convert::class);

?>

<?php if ($config->isEnabled()): ?>
<!-- Begin Convert Experiences Events -->
<script>
    document.addEventListener(
        'load',
        () => convQPush('<?= $escaper->escapeJs($block->getData('event_id')) ?>')
    );
</script>
<!-- End Convert Experiences Events -->
<?php endif; ?>
