<?php

use Elgentos\Convert\ViewModel\Convert;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var Convert $config */
$config = $viewModels->require(Convert::class);

?>

<?php if ($config->isEnabled()): ?>
<!-- Begin Convert Experiences Script -->
<script src="<?= $escaper->escapeUrl($config->getGeneralConvertJsUrl()) ?>"></script>

<script>
    function convQPush(eventId) {
        window._conv_q = window._conv_q || [];
        _conv_q.push(["triggerConversion", eventId]);
    }
</script>
<!-- End Convert Experiences Script -->
<?php endif; ?>
