<?php

/**
 * Copyright Elgentos BV. All rights reserved.
 * https://www.elgentos.nl/
 */

use Elgentos\Convert\ViewModel\Convert;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var Convert $config */
$config = $block->getData('view_model');

?>

<!-- Begin Convert Experiences Script -->
<?php if ($config->isEnabled()): ?>
<script src="<?= $escaper->escapeUrl($config->getGeneralConvertJsUrl()) ?>"></script>

<script>
    function convQPush(eventId) {
        window._conv_q = window._conv_q || [];
        _conv_q.push(["triggerConversion", eventId]);
    }
</script>
<?php else: ?>
    <script>
        function convQPush(eventId) {}
    </script>
<?php endif; ?>
<!-- End Convert Experiences Script -->
